version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db

        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=inventory_db
            - DB_USERNAME=root
            - DB_PASSWORD=123
        ports:
            - "8000:8000"

    db:
        image: mysql:8
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: inventory_db
            MYSQL_ROOT_PASSWORD: 123
